services:
  server: # container hosting REST API and frontend using NodeJS, and Vue.JS
    build: 
        context: ./docker/server
        
    ports:
      - "3000:3000" # Frontend
      - "3033:3033" # REST API
    volumes:
      - ./app:/apps
    depends_on:
      - db
      - mq
  db: # Backend MongoDB container
    build:
        context: ./docker/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=helpdesk
    ports:
      - "27017:27017" # Database Service
    volumes:
      - /data:/data/db
  mq:
    build:
        context: ./docker/mq
    ports:
      - "5672:5672" # RabbitMQ Service
      - "15672:15672" # RabbitMQ Management plugin

networks:
  default:
    driver: bridge