services:
  frontend:
    image: temporalcrow/frontend_server:dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: /bin/sh -c "npm install && npm run dev"
    restart: unless-stopped
  
  backend: # container hosting REST API and frontend using NodeJS, and Vue.JS
    image: ghcr.io/help468/help/backend_server:dev
    ports:
      - "3033:3033"
    depends_on:
      - db
      - mq
    restart: unless-stopped
 
  db: # Backend MongoDB container
    image: mongo
    ports:
      - "27017:27017" # Database Service
    volumes:
      - /data:/data/db
    restart: unless-stopped
 
  mq:
    image: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ Service
      - "15672:15672" # RabbitMQ Management plugin
    restart: unless-stopped

networks:
  default:
    driver: bridge