#Step 1: build the static Vue frontend
FROM node:23-slim AS build

WORKDIR /app

#Copy view source files
COPY frontend/package*.json ./
RUN npm install

COPY frontend .
RUN npm run build

# Step 2: Serve the static webpage with Nginx
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]