name: prod-pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: build && push image to Docker Hub
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push backend
        id: build-push-backend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/server/Dockerfile.prod
          push: true
          tags: temporalcrow/backend_server:latest

      - name: build and push frontend
        id: build-push-vue
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/vue/Dockerfile
          push: true
          tags: temporalcrow/frontend_server:latest
