name: pipeline
on:
  push:
    branches:
      - Docker-Refactor

jobs:
  deploy:
    name: build && push image to Docker Hub
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: Docker-Refactor

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push backend dev (baked-in environment)
        uses: docker/build-push-action@v3
        with:
          context: . # Full Repo access
          file: ./docker/server/Dockerfile.dev
          push: true
          tags: temporalcrow/backend_server:latest
          build-args: |
            MONGODB=${{ secrets.MONGODB }}
            RESTPORT=${{ secrets.RESTPORT }}
            SALTROUND=${{ secrets.SALTROUND }}
      
      - name: build and push backend prod (clean)
        uses: docker/build-push-action@v3
        with:
          context: . # Full Repo access
          file: ./docker/server/Dockerfile.prod
          push: true
          tags: temporalcrow/backend_server:prod

      - name: build and push frontend
        id: build-push-vue
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/vue/Dockerfile
          push: true
          tags: temporalcrow/vue_server:latest
